# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f63330815bfbb7e648fcca4581f29c22146c82f42a371ed9c468ceb5b1abb8ed8debcb74c5a55a039e609d6a52734e68d452a76ca0300a789e6e391c97973956

test:
  secret_key_base: 7d1389b66ee8cfb2721242bff73bfb53ed23710bc12ebcdb702dbd0645ec88dfe53eec988b18e975f0df3ad6019dfde046662db41ca82b11f8ec5fc00fa57564

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
